// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PwaInstallController from "./pwa_install_controller"
application.register("pwa-install", PwaInstallController)

import HabitFormController from "./habit_form_controller"
application.register("habit-form", HabitFormController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import ChecklistController from "./checklist_controller"
application.register("checklist", ChecklistController)

import ChartToggleController from "./chart_toggle_controller"
application.register("chart-toggle", ChartToggleController)
