// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PwaInstallController from "./pwa_install_controller"
application.register("pwa-install", PwaInstallController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import HabitFormController from "./habit_form_controller"
application.register("habit-form", HabitFormController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import ChecklistController from "./checklist_controller"
application.register("checklist", ChecklistController)

import ChartToggleController from "./chart_toggle_controller"
application.register("chart-toggle", ChartToggleController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import TypeToConfirmController from "./type_to_confirm_controller"
application.register("type-to-confirm", TypeToConfirmController)

import LineChartController from "./line_chart_controller"
application.register("line-chart", LineChartController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import RadarChartController from "./radar_chart_controller"
application.register("radar-chart", RadarChartController)

import ScrollEndController from "./scroll_end_controller"
application.register("scroll-end", ScrollEndController)
