// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PwaInstallController from "./pwa_install_controller"
application.register("pwa-install", PwaInstallController)

import HabitFormController from "./habit_form_controller"
application.register("habit-form", HabitFormController)
